version: '3.8'

services:
  app:
    build:
      args:
        work-dir: /var/www/
      context: ./
      dockerfile: Docker/Dockerfile
      target: php
    container_name: books-manager-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - books
  nginx:
    image: nginx:1.19-alpine
    container_name: books-nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/
      - ./Docker/nginx-files:/etc/nginx/conf.d
    networks:
      - books
  mysql:
    image: mysql:8.0
    container_name: books-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
    networks:
      - books
volumes:
  mysql-data-dev:
    driver: local
networks:
  books: